### ISSUE TITLE
\ ( ' O ' ) /

### ISSUE THREAD

**Issue by eonn0** [hey5nee123/javaMaster#1]
바보바부바오밥나무

**Comment by hye5nee123** [comment]
연하녀 왤케 귀여움?

**Comment by eonn0** [comment]
> 연하녀 왤케 귀여움?

![IMG_5024](https://github.com/hey5nee123/javaMaster/assets/152113886/df487b4d-269d-4910-895a-d815466a341c)

**Comment by hye5nee123** [comment]
연하녀 셀카 폼 미쳤다이

**Comment by hey5nee123** [comment]
![20231223_191910.jpg](https://github.com/hey5nee123/javaMaster/assets/152113818/e30a5365-425f-4d1d-a7e1-dda40ffe1685)

연하녀에 취한다...
