### ISSUE TITLE
0103 펼침 연산자,

### ISSUE THREAD

**Issue by hye5nee123** [hey5nee123/javaMaster#10]
펼침 연산자.

>>{...obj1}
커링 함수
>pass
나머지 파라메타

reduce는 (forEach, map,filter) 함수 다음으로...
미련 가지고 한 번은 해보자...
![image](https://github.com/hey5nee123/javaMaster/assets/152113818/5050d376-fd8d-4f8d-94ee-75bc5b560b38)
![image](https://github.com/hey5nee123/javaMaster/assets/152113818/648963e9-e120-42f3-bd37-53fbf8206667)

acc = 초기값
curItem은 현재 진행되는 값 idx = idx 번호 ary = 배열 그 자체 (배열 타입으로 반환해준다는 것인가?)

.var를 웬만해선 쓰지 말라는 거만 알겠음

![image](https://github.com/hey5nee123/javaMaster/assets/152113818/cb97270d-139f-4be5-857b-b9944f3ba759)

**Comment by hye5nee123** [comment]
https://velog.io/@kwonh/ES6-%ED%8E%BC%EC%B9%A8%EC%97%B0%EC%82%B0%EC%9E%90%EC%A0%84%EA%B0%9C%EC%97%B0%EC%82%B0%EC%9E%90-Spread-Syntax-Spread-Operator



https://velog.io/@thyoondev/%EA%B3%A0%EC%B0%A8-%ED%95%A8%EC%88%98higher-order-function%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC


https://yamestyle.com/475


https://velog.io/@sji7532/Python-%EB%82%B4%EC%9E%A5%ED%95%A8%EC%88%98inner-function%EC%99%80-%ED%81%B4%EB%A1%9C%EC%A0%80closure

**Comment by hye5nee123** [comment]
이해불가 화난다

![image](https://github.com/hey5nee123/javaMaster/assets/152113818/5ee9af36-61a9-477d-afa5-989284af643c)


![image](https://github.com/hey5nee123/javaMaster/assets/152113818/76900ddf-d0b0-4ae5-b359-ff1d35bdde47)


랫서판다 귀엽다

**Comment by hye5nee123** [comment]
이거 좀 헷갈리고 신기.

출처 : https://songsong.dev/11


![image](https://github.com/hey5nee123/javaMaster/assets/152113818/78f44183-b16f-495d-a38a-543edd0c72cf)

**Comment by hye5nee123** [comment]
To do.
1.자바스크립트 달력 2번 만들어보기
1.function 사용
2.class 사용 

prototype 공부 이해 불가.
![image](https://github.com/hey5nee123/javaMaster/assets/152113818/6de318b1-cb07-4eb5-ab95-814ec98b8751)

**Comment by hye5nee123** [comment]
https://oa-mall.co.kr/product/detail.html?product_no=657&gad_source=1&gclid=EAIaIQobChMI8573_cTAgwMVxtgWBR2BKARuEAQYASABEgL3sfD_BwE

가습기

**Comment by hye5nee123** [comment]
진짜 놀랐음 ...ㅜ-ㅜ 갑자기 콘솔창 계속 디버깅 맘대로 해버림 ;

https://velog.io/@songjy377/%ED%81%AC%EB%A1%AC-paused-in-debugger-%ED%95%B4%EA%B2%B0%EB%B0%A9%EB%B2%95

해결방법은 의외로 간--단

**Comment by hye5nee123** [comment]
![image](https://github.com/hey5nee123/javaMaster/assets/152113818/02500514-46d7-4a88-9754-a46aa01f0337)


바로 console 창에 출력 해주는 게 나은 듯?

**Comment by hye5nee123** [comment]
![image](https://github.com/hey5nee123/javaMaster/assets/152113818/6722c1c4-cca2-4195-9f88-a575489ba916)
 진짜 신기함...

![image](https://github.com/hey5nee123/javaMaster/assets/152113818/0359a2a9-9e7b-463c-91e2-516a4489ebe6)

**Comment by hye5nee123** [comment]
![image](https://github.com/hey5nee123/javaMaster/assets/152113818/abab03d8-25e3-4659-93f9-0741f6e0b40a)


![image](https://github.com/hey5nee123/javaMaster/assets/152113818/6b788c29-deae-4124-92f9-9ca8b4b2a7a2)

**Comment by Nnagman** [comment]
> https://oa-mall.co.kr/product/detail.html?product_no=657&gad_source=1&gclid=EAIaIQobChMI8573_cTAgwMVxtgWBR2BKARuEAQYASABEgL3sfD_BwE
> 
> 가습기

음... 뭔가요??

**Comment by hye5nee123** [comment]
@Nnagman 저희 학원 공구템이요 ㅎ

**Comment by Nnagman** [comment]
> @Nnagman 저희 학원 공구템이요 ㅎ

앜ㅋㅋ 뭔가 오늘할일 같아보여서 ㅋㅋㅋㅋ

이건 옵션이긴 한데, 이번 이슈나 지난 번 이슈같이 공부한 내용은 TIL 레포에 .md파일로 일자별 만들어서 올리거나 따로 issue용 레포 만들어서 쭉 적는게 좋아보여요! 여긴 레포명이 javaMaster라 누군가 보면 레포명만 보고 지나칠거 같아서요 ! 

issue 매번 잘보고 있어요 👍 저도 보면서 모르는거 있으면 배우고 가요 😂 

TIL 참고할만한 레포 남겨놔요!
https://github.com/Nnagman/TIL  요건 제꺼
https://github.com/jbranchaud/til 이건 검색해보니 star 수가 많네요

**Comment by hye5nee123** [comment]
어려워 보이지만 내일 "도전!" 해보겠습니다,,..
선생님 링크는 안 보여요ㅜㅜ 프라이빗 선언 하셨나요?

**Comment by Nnagman** [comment]
> 어려워 보이지만 내일 "도전!" 해보겠습니다,,.. 선생님 링크는 안 보여요ㅜㅜ 프라이빗 선언 하셨나요?

이제... 퍼블릭 했어요 ㅠㅠ
