### ISSUE TITLE
Self Issue

### ISSUE THREAD

**Issue by hye5nee123** [hey5nee123/javaMaster#2]
lombok 새 dynamic project에서 실행 불가. 
내일 물어봐야할듯 poem.xml 바꿔봤는데 변동 X 뭐가 문제일까 자기 전에 생각해보기 

![image](https://github.com/hey5nee123/javaMaster/assets/152113818/b76709c8-1e0b-441b-9a99-c2101148b8dd)

**Comment by hey5nee123** [comment]
> lombok 새 dynamic project에서 실행 불가. 내일 물어봐야할듯 poem.xml 바꿔봤는데 변동 X 뭐가 문제일까 자기 전에 생각해보기
> 
> ![image](https://private-user-images.githubusercontent.com/152113818/292884149-b76709c8-1e0b-441b-9a99-c2101148b8dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MzUxNjMsIm5iZiI6MTcwMzYzNDg2MywicGF0aCI6Ii8xNTIxMTM4MTgvMjkyODg0MTQ5LWI3NjcwOWM4LTFlMGItNDQxYi05YTk5LWMyMTAxMTQ4YjhkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQyMzU0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTI5MGIxNjlmNDQ1YmVkNjQ1M2M5ZDcwOTRhZDIzNDIzOTcwNWUyZWRkMzQ5ZmIwMjIxMDgwZGJkNzkzODE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xHp8GA--2RLa2FHY4rubr3FGfd-f-NoBE6McFQPl1Kw)

**Comment by hye5nee123** [comment]
근데 개발진스 넘 귀엽다...
