### ISSUE TITLE
23.01.02 

### ISSUE THREAD

**Issue by hye5nee123** [hey5nee123/javaMaster#9]
querySelector()               은 단건 조회( 특정 한 건만 조회 하겠다 (id값 직접 지정 >약간 애매))
querySelectorAll()            은 특정 태그 전체 조회
getElementById()             https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById

함수의 초기 리턴 값은 undefined;

let num = null; (null은 obj)

    let num1;
    let num2 = null;
    console.log(num1 == num2);   //값, 타입 비교.
   비교연산자 이용시 undefined값과 null 값을 같다고 봄(true)

console.log(num1 === num2); 이렇게 하면(타입까지 비교하겠다)
false가 나옴. 

https://2ssue.github.io/common_questions_for_Web_Developer/docs/Javascript/13_undefined&null.html#undefined

![image](https://github.com/hey5nee123/javaMaster/assets/152113818/e64f2c4a-96d9-465e-a1bc-6e216fc40f4d)

![image](https://github.com/hey5nee123/javaMaster/assets/152113818/98c3b4f5-17ce-4295-aa48-de1f871c7130)

![image](https://github.com/hey5nee123/javaMaster/assets/152113818/0daf574c-2aa0-4de9-9562-562d09fea84c)

문자갑을 숫자로 바꿀 수 없을 때 NAN (not a number)으로 표기

삼항연산자.
![image](https://github.com/hey5nee123/javaMaster/assets/152113818/80cbe78b-2735-4c84-bd51-9fb976a37d1c)

오...
![image](https://github.com/hey5nee123/javaMaster/assets/152113818/f93d5560-891f-46ab-ba9c-5edd9ffc11db)

![image](https://github.com/hey5nee123/javaMaster/assets/152113818/7d7f01bd-cc9e-4c79-a3f7-6ceed2bb903a)

![image](https://github.com/hey5nee123/javaMaster/assets/152113818/cc32ddf4-f90f-451d-b18c-88c3a972c838)

![image](https://github.com/hey5nee123/javaMaster/assets/152113818/a34ea433-04bb-4ae4-802c-8d89ccd38538)

2진수 구하기

**Comment by hye5nee123** [comment]
![image](https://github.com/hey5nee123/javaMaster/assets/152113818/12be33cf-ae52-48a4-9b71-68529c095a02)

` ` <안에 넣으면 구문오류 안 일어남

**Comment by hye5nee123** [comment]
![image](https://github.com/hey5nee123/javaMaster/assets/152113818/bc8b160f-1eaf-4a21-9145-f0e7d9f18788)

이거 엄청 중요함!

**Comment by hey5nee123** [comment]
집 가고 싶다

**Comment by hye5nee123** [comment]
![image](https://github.com/hey5nee123/javaMaster/assets/152113818/64f8044b-2eb7-4206-a89d-369e11313210)


![image](https://github.com/hey5nee123/javaMaster/assets/152113818/ed97bcdf-7bf4-42bc-b6b1-723596680db2)
 

?!

**Comment by hye5nee123** [comment]
자꾸 이어지는 개념이라 ...
"가비지 컬렉션"   > 공부 해야할듯..;;;

**Comment by hye5nee123** [comment]
만약 함수 안에서 this를 넣지 않으면 에러가 나거나 전역변수를 찾아올거임.

https://leehwarang.github.io/docs/tech/constructor.html

**Comment by hye5nee123** [comment]
전역변수는...window 객체다 ..?

https://unikys.tistory.com/324 

???

**Comment by hye5nee123** [comment]
화살표 함수 표현식....중요한 기능..ok

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/Arrow_functions
